### PR TITLE
Added a HIDDEN secret message

### PR DESCRIPTION
**Pull request by Applemelon**
This is a desciption

### CODE REVIEW

**Review by JanvanZetten — DISMISSED** [review]
THis comment is a very good addition to the code.


# Please don't change my very good comment 
## -Jan

**Review by asbamse — COMMENTED** [review]
To make a method description, you should use **triple forward slash.**
# "I totally agree" - Jan 2018

**Comment by Applemelon** [comment]
Please look at the new code thy

**Comment by Applemelon** [comment]
Please look at my updated code i made triple slash summary for class

**Review by asbamse — APPROVED** [review]
I love the changes
# "I totally agree" - Jan

**Pull request closed without merging**
